# Generated by Django 4.0.6 on 2022-07-22 05:06

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[video.validators.file_size]),
        ),
    ]
