# Generated by Django 4.0.6 on 2022-07-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
