# Generated by Django 4.0.6 on 2022-07-23 06:12

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_rename_created_at_video_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='uploads/video_files', validators=[video.validators.file_size, video.validators.file_extension]),
        ),
    ]
